## SOCKET directory - /run
# Create directory in /run for location with required permissions
d /run/location 0755 gps gps - -
d /run/loc_client 0775 gps locclient - -
# Create internal directories
d /run/location/ehub 0755 gps gps - -
# selinux context will be set in location.fc file

## DATA directory - /var/lib/location
# Create directory in /var/lib for location with gps:gps permissions
d /var/lib 0755 root root - -
d /var/lib/location 0755 gps gps - -
# Create internal directories
d /var/lib/location/extap_locclient 0755 gps gps - -
# selinux context will be set in location.fc file
